name: note_taking_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  patrol: ^3.5.2

flutter:
  uses-material-design: true

patrol:
  app_name: note_taking_app
  android:
    package_name: com.example.note_taking_app
  ios:
    bundle_id: com.example.note_taking_app
